//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тр ср кнтр.
    /// </summary>
    // *** Start programmer edit section *** (ТрСрКнтр CustomAttributes)

    // *** End programmer edit section *** (ТрСрКнтр CustomAttributes)
    [AutoAltered()]
    [Caption("Справочник транспортные средства контрагентов")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТрСрКнтрE", new string[] {
            "Код as \'Код\'",
            "РегНом as \'Регистрационный номер\'",
            "СпрТранспСр as \'Транспортное средство \'",
            "СпрТранспСр.Наименование as \'Транспортное средство \'",
            "СпрКонтрАг as \'Контрагент\'",
            "СпрКонтрАг.Наименование as \'Контрагент\'"})]
    [View("ТрСрКнтрL", new string[] {
            "Код as \'Код\'",
            "РегНом as \'Регистрационный номер\'",
            "СпрТранспСр.Наименование as \'Транспортное средство \'",
            "СпрКонтрАг.Наименование as \'Контрагент\'"})]
    public class ТрСрКнтр : ICSSoft.STORMNET.DataObject
    {
        
        private int fКод;
        
        private string fРегНом;
        
        private IIS.Kursovaya.СпрКонтрАг fСпрКонтрАг;
        
        private IIS.Kursovaya.СпрТранспСр fСпрТранспСр;
        
        // *** Start programmer edit section *** (ТрСрКнтр CustomMembers)

        // *** End programmer edit section *** (ТрСрКнтр CustomMembers)

        
        /// <summary>
        /// Код.
        /// </summary>
        // *** Start programmer edit section *** (ТрСрКнтр.Код CustomAttributes)

        // *** End programmer edit section *** (ТрСрКнтр.Код CustomAttributes)
        public virtual int Код
        {
            get
            {
                // *** Start programmer edit section *** (ТрСрКнтр.Код Get start)

                // *** End programmer edit section *** (ТрСрКнтр.Код Get start)
                int result = this.fКод;
                // *** Start programmer edit section *** (ТрСрКнтр.Код Get end)

                // *** End programmer edit section *** (ТрСрКнтр.Код Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТрСрКнтр.Код Set start)

                // *** End programmer edit section *** (ТрСрКнтр.Код Set start)
                this.fКод = value;
                // *** Start programmer edit section *** (ТрСрКнтр.Код Set end)

                // *** End programmer edit section *** (ТрСрКнтр.Код Set end)
            }
        }
        
        /// <summary>
        /// РегНом.
        /// </summary>
        // *** Start programmer edit section *** (ТрСрКнтр.РегНом CustomAttributes)

        // *** End programmer edit section *** (ТрСрКнтр.РегНом CustomAttributes)
        [StrLen(255)]
        public virtual string РегНом
        {
            get
            {
                // *** Start programmer edit section *** (ТрСрКнтр.РегНом Get start)

                // *** End programmer edit section *** (ТрСрКнтр.РегНом Get start)
                string result = this.fРегНом;
                // *** Start programmer edit section *** (ТрСрКнтр.РегНом Get end)

                // *** End programmer edit section *** (ТрСрКнтр.РегНом Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТрСрКнтр.РегНом Set start)

                // *** End programmer edit section *** (ТрСрКнтр.РегНом Set start)
                this.fРегНом = value;
                // *** Start programmer edit section *** (ТрСрКнтр.РегНом Set end)

                // *** End programmer edit section *** (ТрСрКнтр.РегНом Set end)
            }
        }
        
        /// <summary>
        /// Тр ср кнтр.
        /// </summary>
        // *** Start programmer edit section *** (ТрСрКнтр.СпрКонтрАг CustomAttributes)

        // *** End programmer edit section *** (ТрСрКнтр.СпрКонтрАг CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрКонтрАг"})]
        [NotNull()]
        public virtual IIS.Kursovaya.СпрКонтрАг СпрКонтрАг
        {
            get
            {
                // *** Start programmer edit section *** (ТрСрКнтр.СпрКонтрАг Get start)

                // *** End programmer edit section *** (ТрСрКнтр.СпрКонтрАг Get start)
                IIS.Kursovaya.СпрКонтрАг result = this.fСпрКонтрАг;
                // *** Start programmer edit section *** (ТрСрКнтр.СпрКонтрАг Get end)

                // *** End programmer edit section *** (ТрСрКнтр.СпрКонтрАг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТрСрКнтр.СпрКонтрАг Set start)

                // *** End programmer edit section *** (ТрСрКнтр.СпрКонтрАг Set start)
                this.fСпрКонтрАг = value;
                // *** Start programmer edit section *** (ТрСрКнтр.СпрКонтрАг Set end)

                // *** End programmer edit section *** (ТрСрКнтр.СпрКонтрАг Set end)
            }
        }
        
        /// <summary>
        /// Тр ср кнтр.
        /// </summary>
        // *** Start programmer edit section *** (ТрСрКнтр.СпрТранспСр CustomAttributes)

        // *** End programmer edit section *** (ТрСрКнтр.СпрТранспСр CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрТранспСр"})]
        [NotNull()]
        public virtual IIS.Kursovaya.СпрТранспСр СпрТранспСр
        {
            get
            {
                // *** Start programmer edit section *** (ТрСрКнтр.СпрТранспСр Get start)

                // *** End programmer edit section *** (ТрСрКнтр.СпрТранспСр Get start)
                IIS.Kursovaya.СпрТранспСр result = this.fСпрТранспСр;
                // *** Start programmer edit section *** (ТрСрКнтр.СпрТранспСр Get end)

                // *** End programmer edit section *** (ТрСрКнтр.СпрТранспСр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТрСрКнтр.СпрТранспСр Set start)

                // *** End programmer edit section *** (ТрСрКнтр.СпрТранспСр Set start)
                this.fСпрТранспСр = value;
                // *** Start programmer edit section *** (ТрСрКнтр.СпрТранспСр Set end)

                // *** End programmer edit section *** (ТрСрКнтр.СпрТранспСр Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТрСрКнтрE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТрСрКнтрE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТрСрКнтрE", typeof(IIS.Kursovaya.ТрСрКнтр));
                }
            }
            
            /// <summary>
            /// "ТрСрКнтрL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТрСрКнтрL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТрСрКнтрL", typeof(IIS.Kursovaya.ТрСрКнтр));
                }
            }
        }
    }
}
