//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч пл з на Д.
    /// </summary>
    // *** Start programmer edit section *** (ТЧПлЗНаД CustomAttributes)

    // *** End programmer edit section *** (ТЧПлЗНаД CustomAttributes)
    [AutoAltered()]
    [Caption("Табличная Часть: Плановая заявка на день")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧПлЗНаДE", new string[] {
            "СтатьиЗатрат as \'Статья затрат\'",
            "СтатьиЗатрат.Наименование as \'Статья затрат\'",
            "СпрНомен as \'Номенклатура\'",
            "СпрНомен.Наименование as \'Номенклатура\'",
            "СпрКонтрАг as \'Контрагент\'",
            "СпрКонтрАг.Наименование as \'Контрагент\'",
            "СпрВидыРаб as \'Вид работы\'",
            "СпрВидыРаб.Наименование as \'Вид работы\'",
            "ТрСрКнтр as \'Транспортное средство контрагента\'",
            "ТрСрКнтр.РегНом as \'Транспортное средство контрагента\'",
            "ОбРаб as \'Объем работ\'",
            "ВремПриб as \'Время прибытия\'",
            "КолЧас as \'Количество часов работы\'",
            "ОбГруз as \'Объем груза\'",
            "СпрЕдИзмер as \'Единица измерения\'",
            "СпрЕдИзмер.Наименование as \'Единица измерения\'"})]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СтатьиЗатрат", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Статья затрат")]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СпрНомен", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номенклатура")]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СпрКонтрАг", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СпрВидыРаб", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Вид работы")]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "ТрСрКнтр", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Транспортное средство контрагента")]
    [MasterViewDefineAttribute("ТЧПлЗНаДE", "СпрЕдИзмер", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Единица измерения")]
    public class ТЧПлЗНаД : ICSSoft.STORMNET.DataObject
    {
        
        private string fОбРаб;
        
        private float fОбГруз;
        
        private string fВремПриб;
        
        private float fКолЧас;
        
        private IIS.Kursovaya.ТрСрКнтр fТрСрКнтр;
        
        private IIS.Kursovaya.СпрНомен fСпрНомен;
        
        private IIS.Kursovaya.СпрЕдИзмер fСпрЕдИзмер;
        
        private IIS.Kursovaya.СпрКонтрАг fСпрКонтрАг;
        
        private IIS.Kursovaya.СтатьиЗатрат fСтатьиЗатрат;
        
        private IIS.Kursovaya.СпрВидыРаб fСпрВидыРаб;
        
        private IIS.Kursovaya.ДокПланЗаНаД fДокПланЗаНаД;
        
        // *** Start programmer edit section *** (ТЧПлЗНаД CustomMembers)

        // *** End programmer edit section *** (ТЧПлЗНаД CustomMembers)

        
        /// <summary>
        /// ВремПриб.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.ВремПриб CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.ВремПриб CustomAttributes)
        [StrLen(255)]
        public virtual string ВремПриб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ВремПриб Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ВремПриб Get start)
                string result = this.fВремПриб;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ВремПриб Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ВремПриб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ВремПриб Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ВремПриб Set start)
                this.fВремПриб = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ВремПриб Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ВремПриб Set end)
            }
        }
        
        /// <summary>
        /// КолЧас.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.КолЧас CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.КолЧас CustomAttributes)
        public virtual float КолЧас
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.КолЧас Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.КолЧас Get start)
                float result = this.fКолЧас;
                // *** Start programmer edit section *** (ТЧПлЗНаД.КолЧас Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.КолЧас Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.КолЧас Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.КолЧас Set start)
                this.fКолЧас = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.КолЧас Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.КолЧас Set end)
            }
        }
        
        /// <summary>
        /// ОбГруз.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.ОбГруз CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.ОбГруз CustomAttributes)
        public virtual float ОбГруз
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбГруз Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбГруз Get start)
                float result = this.fОбГруз;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбГруз Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбГруз Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбГруз Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбГруз Set start)
                this.fОбГруз = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбГруз Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбГруз Set end)
            }
        }
        
        /// <summary>
        /// ОбРаб.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.ОбРаб CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.ОбРаб CustomAttributes)
        [StrLen(255)]
        public virtual string ОбРаб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбРаб Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбРаб Get start)
                string result = this.fОбРаб;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбРаб Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбРаб Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбРаб Set start)
                this.fОбРаб = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ОбРаб Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ОбРаб Set end)
            }
        }
        
        /// <summary>
        /// Т ч пл з на Д.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрВидыРаб"})]
        [NotNull()]
        public virtual IIS.Kursovaya.СпрВидыРаб СпрВидыРаб
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Get start)
                IIS.Kursovaya.СпрВидыРаб result = this.fСпрВидыРаб;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Set start)
                this.fСпрВидыРаб = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрВидыРаб Set end)
            }
        }
        
        /// <summary>
        /// Т ч пл з на Д.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрЕдИзмер"})]
        [NotNull()]
        public virtual IIS.Kursovaya.СпрЕдИзмер СпрЕдИзмер
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Get start)
                IIS.Kursovaya.СпрЕдИзмер result = this.fСпрЕдИзмер;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Set start)
                this.fСпрЕдИзмер = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрЕдИзмер Set end)
            }
        }
        
        /// <summary>
        /// Т ч пл з на Д.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрКонтрАг"})]
        [NotNull()]
        public virtual IIS.Kursovaya.СпрКонтрАг СпрКонтрАг
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Get start)
                IIS.Kursovaya.СпрКонтрАг result = this.fСпрКонтрАг;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Set start)
                this.fСпрКонтрАг = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрКонтрАг Set end)
            }
        }
        
        /// <summary>
        /// Т ч пл з на Д.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СпрНомен CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СпрНомен CustomAttributes)
        [PropertyStorage(new string[] {
                "СпрНомен"})]
        [NotNull()]
        public virtual IIS.Kursovaya.СпрНомен СпрНомен
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрНомен Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрНомен Get start)
                IIS.Kursovaya.СпрНомен result = this.fСпрНомен;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрНомен Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрНомен Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрНомен Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрНомен Set start)
                this.fСпрНомен = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СпрНомен Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СпрНомен Set end)
            }
        }
        
        /// <summary>
        /// Т ч пл з на Д.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат CustomAttributes)
        [PropertyStorage(new string[] {
                "СтатьиЗатрат"})]
        [NotNull()]
        public virtual IIS.Kursovaya.СтатьиЗатрат СтатьиЗатрат
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Get start)
                IIS.Kursovaya.СтатьиЗатрат result = this.fСтатьиЗатрат;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Set start)
                this.fСтатьиЗатрат = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.СтатьиЗатрат Set end)
            }
        }
        
        /// <summary>
        /// Т ч пл з на Д.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.ТрСрКнтр CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.ТрСрКнтр CustomAttributes)
        [PropertyStorage(new string[] {
                "ТрСрКнтр"})]
        [NotNull()]
        public virtual IIS.Kursovaya.ТрСрКнтр ТрСрКнтр
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ТрСрКнтр Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ТрСрКнтр Get start)
                IIS.Kursovaya.ТрСрКнтр result = this.fТрСрКнтр;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ТрСрКнтр Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ТрСрКнтр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ТрСрКнтр Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ТрСрКнтр Set start)
                this.fТрСрКнтр = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ТрСрКнтр Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ТрСрКнтр Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Kursovaya.ДокПланЗаНаД.
        /// </summary>
        // *** Start programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД CustomAttributes)

        // *** End programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ДокПланЗаНаД"})]
        public virtual IIS.Kursovaya.ДокПланЗаНаД ДокПланЗаНаД
        {
            get
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Get start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Get start)
                IIS.Kursovaya.ДокПланЗаНаД result = this.fДокПланЗаНаД;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Get end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Set start)

                // *** End programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Set start)
                this.fДокПланЗаНаД = value;
                // *** Start programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Set end)

                // *** End programmer edit section *** (ТЧПлЗНаД.ДокПланЗаНаД Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧПлЗНаДE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧПлЗНаДE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧПлЗНаДE", typeof(IIS.Kursovaya.ТЧПлЗНаД));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧПлЗНаД.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧПлЗНаД CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧПлЗНаД CustomAttributes)
    public class DetailArrayOfТЧПлЗНаД : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Kursovaya.DetailArrayOfТЧПлЗНаД members)

        // *** End programmer edit section *** (IIS.Kursovaya.DetailArrayOfТЧПлЗНаД members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧПлЗНаД by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧПлЗНаД.
        /// </summary>
        public DetailArrayOfТЧПлЗНаД(IIS.Kursovaya.ДокПланЗаНаД fДокПланЗаНаД) : 
                base(typeof(ТЧПлЗНаД), ((ICSSoft.STORMNET.DataObject)(fДокПланЗаНаД)))
        {
        }
        
        public IIS.Kursovaya.ТЧПлЗНаД this[int index]
        {
            get
            {
                return ((IIS.Kursovaya.ТЧПлЗНаД)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Kursovaya.ТЧПлЗНаД dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
